# Generated by Django 5.2.13 on 2026-04-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="logo",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
